export const SLIDER = {
	INCREMENT_UPPER_BOUND_VALUE: 'INCREMENT_UPPER_BOUND_VALUE',
	DECREMENT_UPPER_BOUND_VALUE: 'DECREMENT_UPPER_BOUND_VALUE',	
	CHANGE_GRAPH_VALUE: 'CHANGE_GRAPH_VALUE',
	TOGGLE_AUTOPLAY: 'TOGGLE_AUTOPLAY',
	DECREMENT_UPPER_BOUND_AND_GRAPH_VALUE: 'DECREMENT_UPPER_BOUND_AND_GRAPH_VALUE'
}
